### ISSUE TITLE
Change default combination of the pieces for thematic tournament play

### ISSUE THREAD

**Issue by musketeerchess** [ianfab/Musketeer-Stockfish#7]
Hi
I'm trying to make some experiments to play thematic tournament using Stockfish as sole engine. The idea is the following Make a tournament using Chancellor and Archbishop (among other combinations) and let the engine play 400 games to see the difference between Musketeer Stockfish and Seirawan Stockfish in terms of draw and win %. 

Unfortunately, it's not possible to setup a sample of positions that can be used by stockfish because the default combination is Leopard and Cannon. The engine keeps skipping the positions using other fairy pieces.

How it's possible to make Stockfish play using another combination of pieces.

Thanks

**Comment by ianfab** [comment]
I assume it is GUI that skips the positions, not the engine. As long as the starting positions are valid, the engine should perfectly be able to play from them. If you can reproduce that a certain position can not be processed by the engine, then please post the FEN here.

**Comment by raphaeleliekakou** [comment]
Hi
The FEN is the following

am******/rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR/AM****** w KQkq - 0 1

Among other. Any combination involving pieces that are different from
default (L and C: leopard and cannon) is automatically skipped by Musketeer
Stockfish.

Attached the Engine pondering.

dep score nodes time (not shown:  tbhits knps seldep)
 16 -0.31 1.47M   0:03.16 U U@c9 U@c0 e7e5 d2d4 e5d4 c2c3 g8f6 c3d4 d7d5
b1c3 f8e7 c1f4 e8g8 g1f3 b8c6 e2e3 c8f5
 15 -0.35 500754 0:01.02 C C@c9 C@d0 e7e5 e2e3 d7d5 d2d4 b8c6 f1b5 e5e4
g1e2 g8f6 e1g1 c8d7 c2c4 a7a6 b5c6 c8c6
 14 -0.30 186308 0:00.35 O O@b9 O@h0 e7e5 d2d4 e5d4 g1f3 d7d5 c1f4 f8c5
f3d4 g8f6 d4b5 e8g8 b5c7
 13 -0.33 90363   0:00.15 O O@d9 O@d0 d7d5 g1f3 g8f6 e2e3 e7e6 f1e2 f8d6
d2d4 e8g8 e1g1
 12 -0.47 58519   0:00.10 O O@c9 O@d0 e7e5 e2e3 d7d5 d2d4 b8c6 b1c3 e5e4
c1d2 g8f6 g1e2
 11 -0.41 27779   0:00.04 C C@c9 C@c0 e7e5 e2e3 d7d5 d2d4 e5e4 c2c4 c7c6
b1c3 g8f6 c4d5
 10 -0.39 12421   0:00.02 D D@d9 D@d0 e7e5 d2d4 e5d4 d1d4 d8e7 d4e3 d7d5
  9 -0.40 2580     0:00.00 C C@c9 C@c0 e7e5 d2d4 e5d4 d1d4 b8c6 d4e3 g8e7
  8 -0.31 667       0:00.00 E E@c9 E@g0 d7d5 d2d4 e7e6 e2e3 c7c5
  7 -0.38 451       0:00.00 E E@c9 E@g0 d7d5 d2d4 e7e6 g1f3
  6 -0.38 361       0:00.00 E E@c9 E@g0 d7d5 d2d4 e7e6
  5 -0.38 292       0:00.00 E E@c9 E@g0 d7d5 d2d4
  4 -0.40 113       0:00.00 C C@c9 C@c0 e7e5 d2d4
  3 -0.40 79         0:00.00 C C@c9 C@c0
  2 -0.40 47         0:00.00 C C@c9 C@c0
  1 -0.40 21         0:00.00 C




Le dim. 26 avr. 2020 à 19:45, Fabian Fichter <notifications@github.com> a
écrit :

**Comment by musketeerchess** [comment]
Hi Raphael
You made the same tests as i asked you.

When making a few moves from
*m***a**/rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR/**A*M*** w KQkq - 0 1

We reach this position after : 1. e4 c5 2. Ke2/M Nc6/M 3. d3 e6 4. Bg5/A
Be7/A 5. c3

********/rmbqkanr/pp1pbppp/2n1p3/2p3B1/4P3/2PP4/PP2KPPP/RNAQMBNR/******** b
kq - 0 5

it's black to move and the engine ponders as follows:

dep score nodes time (not shown:  tbhits knps seldep)
 15 -0.22 1.98M   0:04.14 U U@g9 U@a0 e7e5 e2e4 g8f6 g1f3 f6e4 d2d3 e4f6
f3e5 d8e7 d1e2 d7d5 c2c3 c7c6
 15 -0.30 1.67M   0:03.48 U
 14 -0.22 1.17M   0:02.45 O O@b9 O@b0 e7e5 d2d4 e5d4 g1f3 g8f6 c1f4a b8c6
f3d4 f6d5 c2c3 d5f4
 13 -0.20 770146 0:01.61 O O@a9 O@d0 e7e5 d2d4 e5e4 d4d5 c7c6 c1f4a g8f6
d5d6 f6d5 e2e3 d8f6
 12 -0.32 367946 0:00.76 U U@b9 U@f0 e7e5 d2d4 e5d4 g1f3 g8f6 c1f4a f8b4a
c2c3 d4c3 b2c3 b4e7 e2e3 b8c6
 11 -0.06 170652 0:00.36 U U@b9 U@a0 e7e5 d2d4 e5d4 d1d4 d7d5 g1f3 b8c6
d4e3 b8e7 c2c3
 10 -0.17 99752   0:00.20 U U@d9 U@d0 d7d5 d2d4 b8c6 g1f3 g8f6 e2e3 e7e6
  9 -0.25 43351   0:00.08 S S@c9 S@a0 e7e5 d2d4 e5e4 b1d2 d7d5 e2e3
  8 -0.07 11080   0:00.02 H H@a9 H@a0 g8f6 d2d4 d7d5 e2e3 e7e6
  7 +0.05 2824     0:00.00 H H@a9 H@a0 e7e6 d2d4 d7d5 g1f3
  6 -0.37 1186     0:00.00 H H@a9 H@a0 e7e6 d2d4 d7d5
  5 -0.03 636       0:00.00 H H@a9 H@a0 e7e6 e2e3
  4 -0.67 155       0:00.00 H H@a9 H@a0 e7e6
  3 +0.12 84         0:00.00 H H@a9 H@a0
  2 -6.29 54         0:00.00 H H@a9
  1 +0.12 10         0:00.00 C
  0 #


Le dim. 26 avr. 2020 à 21:33, raphaeleliekakou <notifications@github.com> a
écrit :

**Comment by ianfab** [comment]
How did you do the analysis? Did you play the moves from the starting position, or did you paste the final FEN?

**Comment by musketeerchess** [comment]
Hi
I played the position.

Le dim. 26 avr. 2020 à 23:37, Fabian Fichter <notifications@github.com> a
écrit :

**Comment by ianfab** [comment]
The problem was with the chancellor that had an inconsistency between using piece abbreviations `M` and `O`.
